### ISSUE TITLE
logtailer crash

### ISSUE THREAD

**Issue by lcappuccio** [lcappuccio/filtering-ads-with-linux#4]
```
2016-11-08 22:26:31.841  INFO 25676 --- [nio-8080-exec-3] o.s.a.l.controller.RestController        : Received: config track.zalando.it 192.168.0.4
2016-11-08 22:27:07,813 DEBUG RollingFileManager executing synchronous FileRenameAction[target/debug.log to target/debug-11-08-2016-1.log, renameEmptyFiles=false]
2016-11-08 22:27:07,816 DEBUG RollingFileManager executing synchronous FileRenameAction[target/info.log to target/info-11-08-2016-1.log, renameEmptyFiles=false]
Exception in thread "Thread-2" Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-2"
java.lang.OutOfMemoryError: Java heap space
	at java.lang.StringCoding.decode(StringCoding.java:215)
	at java.lang.String.<init>(String.java:463)
	at java.lang.String.<init>(String.java:515)
	at org.apache.commons.io.input.Tailer.readLines(Tailer.java:528)
	at org.apache.commons.io.input.Tailer.run(Tailer.java:470)
	at java.lang.Thread.run(Thread.java:745)
2016-11-08 22:28:54,685 DEBUG Stopping LoggerContext[name=26253138, org.apache.logging.log4j.core.LoggerContext@8b7f67]
2016-11-08 22:28:54,687 DEBUG Stopping LoggerContext[name=26253138, org.apache.logging.log4j.core.LoggerContext@8b7f67]...
2016-11-08 22:28:54,688 DEBUG Unregistering MBean org.apache.logging.log4j2:type=26253138
2016-11-08 22:28:54,689 DEBUG Unregistering MBean org.apache.logging.log4j2:type=26253138,component=StatusLogger
2016-11-08 22:28:54,690 DEBUG Unregistering MBean org.apache.logging.log4j2:type=26253138,component=ContextSelector
2016-11-08 22:28:54,691 DEBUG Unregistering MBean org.apache.logging.log4j2:type=26253138,component=Loggers,name=
2016-11-08 22:28:54,692 DEBUG Unregistering MBean org.apache.logging.log4j2:type=26253138,component=Appenders,name=debug_logfile
2016-11-08 22:28:54,693 DEBUG Unregistering MBean org.apache.logging.log4j2:type=26253138,component=Appenders,name=info_logfile
2016-11-08 22:28:54,693 DEBUG Unregistering MBean org.apache.logging.log4j2:type=26253138,component=Appenders,name=error_logfile
2016-11-08 22:28:54,698 DEBUG Shutting down RollingFileManager target/info.log
2016-11-08 22:28:54,698 DEBUG Shutting down RollingFileManager target/error.log
2016-11-08 22:28:54,699 DEBUG Shutting down RollingFileManager target/debug.log
2016-11-08 22:28:54,699 DEBUG Stopped XmlConfiguration[location=jar:file:/home/pi/Programs/adtrap/logtailer-1.0.2-SNAPSHOT-jar-with-dependencies.jar!/log4j2.xml] OK
2016-11-08 22:28:54,700 DEBUG Stopped LoggerContext[name=26253138, org.apache.logging.log4j.core.LoggerContext@8b7f67]...
```

**Comment by lcappuccio** [comment]
Probably need to increase memory size in `launch_all.sh`:

`nohup java -Xmx128m -Xms64m -jar logtailer-1.0-jar-with-dependencies.jar -f /var/log/dnsmasq.log -s 1000 &
`
to
`nohup java -Xmx256m -Xms128m -jar logtailer-1.0-jar-with-dependencies.jar -f /var/log/dnsmasq.log -s 1000 &`

**Comment by lcappuccio** [comment]
Possibly error not due to dnsmasq log rotation but to own log4j log rotation.

**Comment by lcappuccio** [comment]
logtailer merged with logarchiver and became adtrap!
memory occupation reduced.
